server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  # Angular Router: sve nepoznate rute vrati na index.html
  # (bez ovoga refresh na npr. /trips/5 daje 404)
  location / {
    try_files $uri $uri/ /index.html;
  }
}
